### PR TITLE
Merge latest changes from upstream

### PR DESCRIPTION
**Pull request by fsfod**
Merge the latest fixes and changes from the upstream LuaJIT repo into our master

### CODE REVIEW

**Comment by ltratt** [comment]
I guess we should rebase these against master and then merge?

**Comment by fsfod** [comment]
I didn't think it needed a rebase

**Comment by ltratt** [comment]
Well, we do have a lot of "merge master" commits which are ugly. But, admittedly, rebasing might cause all the commit hashes to go out of the sync with the main LuaJIT repository. Can you give it a go and see what happens? If all the hashes change, then maybe we should stick with what we have.

**Comment by fsfod** [comment]
I think i explained this before he tries to commit fixes to the v2.0 branch which is also used as the master branch. The fixes are then ported forward by merging the tip of v2.0 in to v2.1

**Comment by ltratt** [comment]
Yes, I understand that, but it doesn't address my comment which is about the merge commits. Were they introduced by us? [If so, I'd like to try rebasing to get rid of them] Or are they present in the original repo?

**Comment by fsfod** [comment]
They not introduced to by us there part of upstream created when fixes are merged from v2.0/master in to v2.1 branch.

**Comment by ltratt** [comment]
Right, so merge as-is then?

**Review by ltratt — APPROVED** [review]

**Comment by fsfod** [comment]
yep just merge it

**Pull request merged**
